exports.songs = [
  {
    photo: "photo",
    title: "Te Felicito",
    duration: 189,
    genre: "Pop",
    releaseDate: "2022",
  },
  {
    photo: "photo",
    title: "Bonito",
    duration: 246,
    genre: "Rock en español",
    releaseDate: "2003",
  },
  {
    photo: "photo",
    title: "Tu vida en la mía",
    duration: 370,
    genre: "Salsa",
    releaseDate: "2019",
  },
  {
    photo: "photo",
    title: "Ojalá que llueva café",
    duration: 240,
    genre: "Merengue",
    releaseDate: "1989",
  },
  {
    photo: "photo",
    title: "Perfect",
    duration: 460,
    genre: "Pop",
    releaseDate: "2001",
  },
  {
    photo: "photo",
    title: "La bilirrubina",
    duration: 240,
    genre: "Merengue",
    releaseDate: "1990",
  },
  {
    photo: "photo",
    title: "Just the way you are",
    duration: 264,
    genre: "Pop",
    releaseDate: "2017",
  },
  {
    photo: "photo",
    title: "Everybody",
    duration: 244,
    genre: "Pop",
    releaseDate: "1997",
  },
];
